"""leakguard bench - precision/recall on the labelled test corpus (P4 Task 3).

Runs analyze() against every file in tests/corpus/{safe,leaky}/ and compares
the result against each file's # EXPECT: directive (see tests/test_corpus.py)
to compute a confusion matrix. bench is a report, not a gate - it always
exits 0 and never blocks CI; it exists to make the precision/recall number
real and regeneratable on demand instead of a claim in a slide.

Every run rewrites docs/03-benchmark.md so the doc is never stale.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from leakguard import analyze
from leakguard.config import Config
from leakguard.engine import engine_available

DIRECTIVE = re.compile(
    r"#\s*EXPECT:\s*(CLEAN|LEAK)(?:\s+var=(\S+))?"
    r"(?:\s+line=(\d+))?(?:\s+confidence=(\w+))?"
)

REPO_ROOT = Path(__file__).resolve().parent.parent


def expectations(path: Path) -> list[dict]:
    """Parse the # EXPECT: header(s) at the top of a corpus file."""
    out: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = DIRECTIVE.match(line.strip())
        if not m:
            continue
        kind, var, line_no, conf = m.groups()
        if kind == "CLEAN":
            return []
        out.append(
            {
                "var": var,
                "line": int(line_no) if line_no else None,
                "confidence": conf,
            }
        )
    return out


def run_bench(corpus_root: Path) -> int:
    tp = fp = tn = fn = 0
    rows: list[tuple[Path, bool, bool]] = []

    for path in sorted(corpus_root.rglob("*.py")):
        expected = expectations(path)
        actual = analyze([path], Config())
        is_leaky, flagged = bool(expected), bool(actual)

        if is_leaky and flagged:
            tp += 1
        elif is_leaky and not flagged:
            fn += 1
        elif not is_leaky and flagged:
            fp += 1
        else:
            tn += 1
        rows.append((path.relative_to(corpus_root), is_leaky, flagged))

    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0

    print(_format_report(tp, fp, tn, fn, precision, recall, f1))

    if not engine_available():
        print(
            "leakguard: WARNING - analysis engine not wired up yet; "
            "results are stub data (see leakguard/engine.py)"
        )

    _write_doc(tp, fp, tn, fn, precision, recall, f1, rows)
    return 0


def _format_report(
    tp: int, fp: int, tn: int, fn: int, precision: float, recall: float, f1: float
) -> str:
    return (
        "\n"
        "              flagged   clean\n"
        f"    leaky      TP {tp:3d}   FN {fn:3d}\n"
        f"    safe       FP {fp:3d}   TN {tn:3d}\n"
        "\n"
        f"    precision {precision:.2f}   recall {recall:.2f}   F1 {f1:.2f}\n"
    )


def _write_doc(
    tp: int,
    fp: int,
    tn: int,
    fn: int,
    precision: float,
    recall: float,
    f1: float,
    rows: list[tuple[Path, bool, bool]],
) -> None:
    doc_path = REPO_ROOT / "docs" / "03-benchmark.md"
    doc_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Benchmark",
        "",
        "Generated by `leakguard bench` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. "
        "Regenerate with `leakguard bench` - do not hand-edit.",
        "",
        "```",
        "              flagged   clean",
        f"    leaky      TP {tp:3d}   FN {fn:3d}",
        f"    safe       FP {fp:3d}   TN {tn:3d}",
        "",
        f"    precision {precision:.2f}   recall {recall:.2f}   F1 {f1:.2f}",
        "```",
        "",
        "## Per-file results",
        "",
        "| File | Should flag | Flagged | Result |",
        "|---|---|---|---|",
    ]
    for rel_path, is_leaky, flagged in rows:
        result = "correct" if is_leaky == flagged else "**WRONG**"
        lines.append(
            f"| `{rel_path.as_posix()}` | {'leak' if is_leaky else 'clean'} | "
            f"{'leak' if flagged else 'clean'} | {result} |"
        )
    lines.append("")

    doc_path.write_text("\n".join(lines), encoding="utf-8")
