"use client";

import { useEffect, useMemo, useState } from "react";
import { organizationSnapshot, type OrganizationSnapshot } from "@/lib/organization";

type View = "overview" | "employees" | "repositories" | "incidents";

function useOrganization() {
  const [data, setData] = useState(organizationSnapshot);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void fetch("/api/organization").then((r) => r.ok ? r.json() : Promise.reject()).then(setData).finally(() => setLoading(false)); }, []);
  return { data, loading };
}

function Metrics({ data }: { data: OrganizationSnapshot }) {
  const items = [["Employees", data.metrics.employees], ["Repositories", data.metrics.repositories], ["Open incidents", data.metrics.open], ["Blocked PRs", data.metrics.blockedPrs], ["Fix rate", `${data.metrics.fixRate}%`], ["CI scans", data.metrics.scans]];
  return <section className="admin-metrics">{items.map(([label, value]) => <div className="admin-stat" key={label}><small>{label}</small><b>{value}</b></div>)}</section>;
}

function EmployeeTable({ data, compact = false }: { data: OrganizationSnapshot; compact?: boolean }) {
  const employees = useMemo(() => [...data.employees].sort((a, b) => b.score - a.score), [data]);
  return <section className="admin-card"><div className="admin-card-head"><div><span className="panel-kicker">Team security performance</span><h2>{compact ? "Employee risk leaderboard" : "All employees"}</h2></div><span className="admin-help">Accuracy = clean PR checks / total PR checks</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Rank / employee</th><th>Security score</th><th>Clean accuracy</th><th>D / L / P errors</th><th>Blocked PRs</th><th>Fix rate</th><th>Avg fix</th></tr></thead><tbody>{employees.map((employee, index) => <tr key={employee.login}><td><span className="rank">#{index + 1}</span><span className="avatar">{employee.avatar}</span><strong>{employee.name}<small>@{employee.login} · {employee.scans} checks</small></strong></td><td><b className={employee.score < 60 ? "danger-text" : "good-text"}>{employee.score}</b><span className="score-track"><i style={{ width: `${employee.score}%` }}/></span></td><td><b className={employee.cleanRate < 60 ? "danger-text" : "good-text"}>{employee.cleanRate}%</b></td><td><span className="severity-count definite">{employee.definite}</span><span className="severity-count likely">{employee.likely}</span><span className="severity-count possible">{employee.possible}</span></td><td>{employee.blocked}</td><td>{employee.fixRate}%<small>{employee.fixed} fixed</small></td><td>{employee.avgFixHours}h</td></tr>)}</tbody></table></div></section>;
}

function EmployeeDirectory({ data }: { data: OrganizationSnapshot }) {
  const ordered = [...data.employees].sort((a, b) => a.score - b.score);
  const [selected, setSelected] = useState(ordered[0].login);
  const employee = data.employees.find((item) => item.login === selected) ?? ordered[0];
  const incidents = data.incidents.filter((item) => item.employee === employee.login);
  return <section className="directory-layout"><aside className="employee-list"><header><span className="panel-kicker">Directory</span><strong>{data.employees.length} monitored employees</strong></header>{ordered.map((item) => <button className={item.login === employee.login ? "active" : ""} key={item.login} onClick={() => setSelected(item.login)}><span className="avatar">{item.avatar}</span><span><strong>{item.name}</strong><small>@{item.login} · {item.open} open</small></span><b className={item.score < 60 ? "danger-text" : "good-text"}>{item.score}</b></button>)}</aside><article className="employee-profile"><header><div><span className="panel-kicker">Combined across all repositories</span><h2>{employee.name} <small>@{employee.login}</small></h2></div><span className={`profile-score ${employee.score < 60 ? "risk" : "healthy"}`}><b>{employee.score}</b><small>security score</small></span></header><div className="profile-kpis"><span><small>Clean-check accuracy</small><b>{employee.cleanRate}%</b></span><span><small>Open errors</small><b>{employee.open}</b></span><span><small>Fix rate</small><b>{employee.fixRate}%</b></span><span><small>Mean time to fix</small><b>{employee.avgFixHours}h</b></span><span><small>Repeat errors</small><b>{employee.repeats}</b></span></div><div className="profile-columns"><div><h3>Repository performance</h3>{employee.repositories.map((repo) => <div className="repo-contribution" key={repo.repository}><strong>{repo.repository}<small>{repo.checks} PR checks · {repo.blocked} blocked</small></strong><span><b>{repo.cleanRate}%</b><small>accuracy</small></span><em>{repo.errors} errors</em></div>)}</div><div><h3>Recent attributed errors</h3>{incidents.length ? incidents.map((incident) => <div className="profile-incident" key={incident.id}><span className={`severity ${incident.confidence}`}>{incident.confidence}</span><strong>{incident.resource}<small>{incident.repository} · {incident.file}</small></strong><em>PR #{incident.pr}</em></div>) : <p className="empty-state">No recent errors for this employee.</p>}</div></div></article></section>;
}

function RepoPortfolio({ data, detailed = false }: { data: OrganizationSnapshot; detailed?: boolean }) {
  return <section className={detailed ? "repository-stack" : "repo-risk-grid"}>{data.repositories.map((repo) => {
    const incidents = data.incidents.filter((item) => item.repository === repo.name);
    if (!detailed) return <article className={`repo-risk ${repo.risk}`} key={repo.name}><div><span className="repo-symbol">R</span><span><strong>{repo.name}</strong><small>{repo.language} · {repo.members.length} employees</small></span></div><b>{repo.open}<small>open incidents</small></b><footer><span>{repo.blockedPrs} PRs blocked</span><em>{repo.risk} risk</em></footer></article>;
    return <article className={`repository-panel ${repo.risk}`} key={repo.name}><header><div><span className="repo-symbol">R</span><span><h2>{repo.name}</h2><small>{repo.language} · {repo.scans} incremental checks · {repo.members.length} contributors</small></span></div><div className="repo-summary"><span><b>{repo.open}</b><small>open errors</small></span><span><b>{repo.blockedPrs}</b><small>blocked PRs</small></span><em>{repo.risk} risk</em></div></header><div className="repository-body"><div><h3>Employees in this repository</h3><table className="repo-member-table"><thead><tr><th>Employee</th><th>Checks</th><th>Accuracy</th><th>Errors</th><th>Blocked</th></tr></thead><tbody>{repo.members.map((member) => { const person = data.employees.find((item) => item.login === member.login); return <tr key={member.login}><td><span className="avatar">{person?.avatar}</span><strong>{person?.name}<small>@{member.login}</small></strong></td><td>{member.checks}</td><td><b className={member.cleanRate < 60 ? "danger-text" : "good-text"}>{member.cleanRate}%</b></td><td>{member.errors}</td><td>{member.blocked}</td></tr>; })}</tbody></table></div><div><h3>Repository incidents</h3>{incidents.length ? incidents.map((incident) => <div className="repo-incident" key={incident.id}><header><span className={`severity ${incident.confidence}`}>{incident.confidence}</span><b>{incident.id}</b><em>{incident.status}</em></header><strong>{incident.resource}</strong><small>@{incident.employee} · PR #{incident.pr}</small><code>{incident.file}</code><span className={`gate ${incident.gate}`}>{incident.gate === "blocked" ? "Merge blocked" : "Resolved"}</span></div>) : <p className="empty-state">No repository incidents.</p>}</div></div></article>;
  })}</section>;
}

function IncidentTable({ data, limit }: { data: OrganizationSnapshot; limit?: number }) {
  const incidents = limit ? data.incidents.slice(0, limit) : data.incidents;
  return <section className="admin-card"><div className="admin-card-head"><div><span className="panel-kicker">GitHub enforcement</span><h2>Recent incidents</h2></div><span className="admin-help">Only changed Python files scanned</span></div><div className="admin-table-wrap"><table className="admin-table incident-table"><thead><tr><th>Incident</th><th>Employee / repository</th><th>Finding</th><th>Pull request</th><th>Gate</th></tr></thead><tbody>{incidents.map((incident) => <tr key={incident.id}><td><strong>{incident.id}</strong><small>{incident.detectedAt}</small></td><td><strong>@{incident.employee}</strong><small>{incident.repository} · {incident.branch}</small></td><td><span className={`severity ${incident.confidence}`}>{incident.confidence}</span><strong>{incident.resource}</strong><small>{incident.file}</small></td><td>#{incident.pr}</td><td><span className={`gate ${incident.gate}`}>{incident.gate === "blocked" ? "× Merge blocked" : "✓ Merge allowed"}</span></td></tr>)}</tbody></table></div></section>;
}

export function AdminDashboard({ view }: { view: View }) {
  const { data, loading } = useOrganization();
  const titles = { overview: ["Organization command center", "Security posture across every employee, repository and protected pull request."], employees: ["Employee security", "Compare exact leak types, clean-check accuracy and remediation performance."], repositories: ["Repository risk", "Prioritize repositories carrying the highest unresolved resource-leak debt."], incidents: ["Leak incidents", "Audit every finding attributed to its employee, branch, commit and pull request."] };
  return <>{loading && <div className="admin-loading"><i/> Syncing organization data</div>}<div className="admin-top"><div><span className="eyebrow">LeakGuard Organization</span><h1 className="page-title">{titles[view][0]}</h1><p className="subtitle">{titles[view][1]}</p></div><div className="org-chip"><span>CB</span><strong>{data.organization}<small>{data.source === "control-plane" ? "Live control plane" : "Demo organization data"}</small></strong></div></div>{view === "overview" && <><Metrics data={data}/><div className="admin-section-title"><h2>Repository portfolio</h2><span>Updated from GitHub Actions</span></div><RepoPortfolio data={data}/><EmployeeTable data={data} compact/><IncidentTable data={data} limit={3}/></>}{view === "employees" && <><EmployeeDirectory data={data}/><EmployeeTable data={data}/></>}{view === "repositories" && <RepoPortfolio data={data} detailed/>}{view === "incidents" && <><Metrics data={data}/><IncidentTable data={data}/></>}</>;
}
