"use client";

import { Fragment, useEffect, useMemo, useState } from "react";
import { organizationSnapshot, type OrganizationSnapshot } from "@/lib/organization";

type View = "overview" | "employees" | "repositories" | "incidents";

function useOrganization(filters: { range: string; search: string; repository: string; employee: string }) {
  const [data, setData] = useState(organizationSnapshot);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    const query = new URLSearchParams({ ...filters, pageSize: "50" });
    const timer = window.setTimeout(() => { setLoading(true); void fetch(`/api/organization?${query}`).then((r) => r.ok ? r.json() : Promise.reject()).then(setData).finally(() => setLoading(false)); }, 180);
    return () => window.clearTimeout(timer);
  }, [filters.range, filters.search, filters.repository, filters.employee]);
  return { data, loading };
}

function FilterBar({ data, filters, setFilters }: { data: OrganizationSnapshot; filters: { range: string; search: string; repository: string; employee: string }; setFilters: (next: typeof filters) => void }) {
  return <section className="filter-bar"><div><label htmlFor="org-search">Search employee, repo, error or reason</label><input id="org-search" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} placeholder="Search organization..."/></div><div><label htmlFor="date-range">Date range</label><select id="date-range" value={filters.range} onChange={(event) => setFilters({ ...filters, range: event.target.value })}><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select></div><div><label htmlFor="repo-filter">Repository</label><select id="repo-filter" value={filters.repository} onChange={(event) => setFilters({ ...filters, repository: event.target.value })}><option value="all">All repositories</option>{organizationSnapshot.repositories.map((repo) => <option key={repo.name}>{repo.name}</option>)}</select></div><div><label htmlFor="employee-filter">Employee</label><select id="employee-filter" value={filters.employee} onChange={(event) => setFilters({ ...filters, employee: event.target.value })}><option value="all">All employees</option>{organizationSnapshot.employees.map((employee) => <option value={employee.login} key={employee.login}>{employee.name}</option>)}</select></div><button onClick={() => setFilters({ range: "7d", search: "", repository: "all", employee: "all" })}>Reset</button><small>{data.pagination ? `${data.pagination.totalEmployees} employees · ${data.pagination.totalIncidents} incidents` : "Organization scope"}</small></section>;
}

function DailyTrend({ data }: { data: OrganizationSnapshot }) {
  const max = Math.max(...data.trend.map((point) => point.opened), 1);
  return <section className="daily-panel"><header><div><span className="panel-kicker">Daily movement</span><h2>Is the team improving?</h2></div><div className="today-comparison"><b className="good-text">+{data.metrics.cleanRateDelta}%</b><small>clean accuracy</small><b className="good-text">{data.metrics.openDelta}</b><small>open errors</small></div></header><div className="daily-chart">{data.trend.map((point) => <div className="day-column" key={point.date}><span className="accuracy-label">{point.accuracy}%</span><div className="day-bars"><i className="bar-opened" style={{ height: `${Math.max(8, point.opened / max * 100)}%` }}/><i className="bar-resolved" style={{ height: `${Math.max(8, point.fixed / max * 100)}%` }}/></div><small>{point.date}</small></div>)}</div><footer><span><i className="bar-opened"/> errors opened</span><span><i className="bar-resolved"/> errors fixed</span><strong>Today: {data.trend.at(-1)?.fixed} fixed vs {data.trend.at(-1)?.opened} opened</strong></footer></section>;
}

function PersonalProgress({ employee, data }: { employee: OrganizationSnapshot["employees"][number]; data: OrganizationSnapshot }) {
  const points = data.trend.map((point, index) => ({ ...point, personal: Math.max(20, Math.min(100, employee.cleanRate - employee.cleanRateDelta + employee.cleanRateDelta * index / Math.max(1, data.trend.length - 1))) }));
  return <section className="personal-progress"><header><div><span className="panel-kicker">Personal progress</span><h3>{employee.name}&apos;s clean-check trend</h3></div><b className={employee.cleanRateDelta >= 0 ? "good-text" : "danger-text"}>{employee.cleanRateDelta >= 0 ? "+" : ""}{employee.cleanRateDelta}%</b></header><div className="personal-bars">{points.map((point) => <div key={point.date}><span style={{ height: `${point.personal}%` }}/><b>{Math.round(point.personal)}%</b><small>{point.date}</small></div>)}</div><footer>Calculated from this employee&apos;s clean PR checks in the selected period.</footer></section>;
}

function Metrics({ data }: { data: OrganizationSnapshot }) {
  const items = [["Employees", data.metrics.employees], ["Repositories", data.metrics.repositories], ["Open incidents", data.metrics.open], ["Blocked PRs", data.metrics.blockedPrs], ["Fix rate", `${data.metrics.fixRate}%`], ["CI scans", data.metrics.scans]];
  return <section className="admin-metrics">{items.map(([label, value]) => <div className="admin-stat" key={label}><small>{label}</small><b>{value}</b></div>)}</section>;
}

function EmployeeTable({ data, compact = false }: { data: OrganizationSnapshot; compact?: boolean }) {
  const employees = useMemo(() => [...data.employees].sort((a, b) => b.score - a.score), [data]);
  return <section className="admin-card"><div className="admin-card-head"><div><span className="panel-kicker">Team security performance</span><h2>{compact ? "Employee risk leaderboard" : "All employees"}</h2></div><span className="admin-help">Accuracy = clean PR checks / total PR checks</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Rank / employee</th><th>Security score</th><th>Clean accuracy</th><th>D / L / P errors</th><th>Blocked PRs</th><th>Fix rate</th><th>Avg fix</th></tr></thead><tbody>{employees.map((employee, index) => <tr key={employee.login}><td><span className="rank">#{index + 1}</span><span className="avatar">{employee.avatar}</span><strong>{employee.name}<small>@{employee.login} · {employee.scans} checks</small></strong></td><td><b className={employee.score < 60 ? "danger-text" : "good-text"}>{employee.score}</b><span className="score-track"><i style={{ width: `${employee.score}%` }}/></span></td><td><b className={employee.cleanRate < 60 ? "danger-text" : "good-text"}>{employee.cleanRate}%</b></td><td><span className="severity-count definite">{employee.definite}</span><span className="severity-count likely">{employee.likely}</span><span className="severity-count possible">{employee.possible}</span></td><td>{employee.blocked}</td><td>{employee.fixRate}%<small>{employee.fixed} fixed</small></td><td>{employee.avgFixHours}h</td></tr>)}</tbody></table></div></section>;
}

function EmployeeDirectory({ data }: { data: OrganizationSnapshot }) {
  const ordered = [...data.employees].sort((a, b) => a.score - b.score);
  const [selected, setSelected] = useState(ordered[0].login);
  const employee = data.employees.find((item) => item.login === selected) ?? ordered[0];
  const incidents = data.incidents.filter((item) => item.employee === employee.login);
  return <section className="directory-layout"><aside className="employee-list"><header><span className="panel-kicker">Directory</span><strong>{data.employees.length} monitored employees</strong></header>{ordered.map((item) => <button className={item.login === employee.login ? "active" : ""} key={item.login} onClick={() => setSelected(item.login)}><span className="avatar">{item.avatar}</span><span><strong>{item.name}</strong><small>@{item.login} · {item.open} open</small></span><b className={item.score < 60 ? "danger-text" : "good-text"}>{item.score}</b></button>)}</aside><article className="employee-profile"><header><div><span className="panel-kicker">Combined across all repositories</span><h2>{employee.name} <small>@{employee.login}</small></h2></div><span className={`profile-score ${employee.score < 60 ? "risk" : "healthy"}`}><b>{employee.score}</b><small>security score</small></span></header><div className="profile-kpis"><span><small>Clean-check accuracy</small><b>{employee.cleanRate}%</b></span><span><small>Open errors</small><b>{employee.open}</b></span><span><small>Fix rate</small><b>{employee.fixRate}%</b></span><span><small>Mean time to fix</small><b>{employee.avgFixHours}h</b></span><span><small>Repeat errors</small><b>{employee.repeats}</b></span></div><PersonalProgress employee={employee} data={data}/><div className="profile-columns"><div><h3>Repository performance</h3>{employee.repositories.map((repo) => <div className="repo-contribution" key={repo.repository}><strong>{repo.repository}<small>{repo.checks} PR checks · {repo.blocked} blocked</small></strong><span><b>{repo.cleanRate}%</b><small>accuracy</small></span><em>{repo.errors} errors</em></div>)}</div><div><h3>Recent attributed errors</h3>{incidents.length ? incidents.map((incident) => <div className="profile-incident" key={incident.id}><span className={`severity ${incident.confidence}`}>{incident.confidence}</span><strong>{incident.resource}<small>{incident.repository} · {incident.file}</small></strong><em>PR #{incident.pr}</em></div>) : <p className="empty-state">No recent errors for this employee.</p>}</div></div></article></section>;
}

function RepoPortfolio({ data, detailed = false }: { data: OrganizationSnapshot; detailed?: boolean }) {
  return <section className={detailed ? "repository-stack" : "repo-risk-grid"}>{data.repositories.map((repo) => {
    const incidents = data.incidents.filter((item) => item.repository === repo.name);
    if (!detailed) return <article className={`repo-risk ${repo.risk}`} key={repo.name}><div><span className="repo-symbol">R</span><span><strong>{repo.name}</strong><small>{repo.language} · {repo.members.length} employees</small></span></div><b>{repo.open}<small>open incidents</small></b><footer><span>{repo.blockedPrs} PRs blocked</span><em>{repo.risk} risk</em></footer></article>;
    return <article className={`repository-panel ${repo.risk}`} key={repo.name}><header><div><span className="repo-symbol">R</span><span><h2>{repo.name}</h2><small>{repo.language} · {repo.scans} incremental checks · {repo.members.length} contributors · {repo.teams.length} teams</small></span></div><div className="repo-summary"><span><b>{repo.open}</b><small>open errors</small></span><span><b>{repo.blockedPrs}</b><small>blocked PRs</small></span><em>{repo.risk} risk</em></div></header><div className="team-strip">{repo.teams.map((team) => <div className="team-card" key={team.name}><header><strong>{team.name}</strong><span className={team.cleanRate < 60 ? "danger-text" : "good-text"}>{team.cleanRate}% clean</span></header><small>Lead @{team.lead} · {team.members.length} members</small><div><span><b>{team.open}</b> open</span><span><b>{team.blocked}</b> blocked</span></div></div>)}</div><div className="repository-body"><div><h3>Employees in this repository</h3><table className="repo-member-table"><thead><tr><th>Employee</th><th>Checks</th><th>Accuracy</th><th>Errors</th><th>Blocked</th></tr></thead><tbody>{repo.members.map((member) => { const person = data.employees.find((item) => item.login === member.login); return <tr key={member.login}><td><span className="avatar">{person?.avatar}</span><strong>{person?.name}<small>@{member.login}</small></strong></td><td>{member.checks}</td><td><b className={member.cleanRate < 60 ? "danger-text" : "good-text"}>{member.cleanRate}%</b></td><td>{member.errors}</td><td>{member.blocked}</td></tr>; })}</tbody></table></div><div><h3>Repository incidents</h3>{incidents.length ? incidents.map((incident) => <div className="repo-incident" key={incident.id}><header><span className={`severity ${incident.confidence}`}>{incident.confidence}</span><b>{incident.id}</b><em>{incident.status}</em></header><strong>{incident.resource}</strong><small>@{incident.employee} · PR #{incident.pr}</small><code>{incident.file}</code><span className={`gate ${incident.gate}`}>{incident.gate === "blocked" ? "Merge blocked" : "Resolved"}</span></div>) : <p className="empty-state">No repository incidents.</p>}</div></div></article>;
  })}</section>;
}

function IncidentTable({ data, limit }: { data: OrganizationSnapshot; limit?: number }) {
  const [selected, setSelected] = useState<string | null>(null);
  const incidents = limit ? data.incidents.slice(0, limit) : data.incidents;
  return <section className="admin-card"><div className="admin-card-head"><div><span className="panel-kicker">GitHub enforcement</span><h2>Employee errors with reasons</h2></div><span className="admin-help">Click for reasoning and technical evidence</span></div><div className="admin-table-wrap"><table className="admin-table incident-table"><thead><tr><th>Incident</th><th>Employee / repository</th><th>Finding</th><th>Pull request</th><th>Gate</th></tr></thead><tbody>{incidents.map((incident) => <Fragment key={incident.id}><tr className="clickable-incident" onClick={() => setSelected(selected === incident.id ? null : incident.id)}><td><strong>{incident.id}</strong><small>{incident.detectedAt}</small></td><td><strong>@{incident.employee}</strong><small>{incident.repository} · {incident.branch}</small></td><td><span className={`severity ${incident.confidence}`}>{incident.confidence}</span><strong>{incident.resource}</strong><small>{incident.file}</small></td><td>#{incident.pr}</td><td><span className={`gate ${incident.gate}`}>{incident.gate === "blocked" ? "Blocked" : "Allowed"}</span></td></tr>{selected === incident.id && <tr className="incident-evidence"><td colSpan={5}><div><span><small>Why LeakGuard flagged it</small><strong>{incident.reason}</strong><em>Coaching context for @{incident.employee}</em></span><span><small>Technical witness path</small><ol>{incident.leakPath.map((step) => <li key={step}>{step}</li>)}</ol></span></div></td></tr>}</Fragment>)}</tbody></table></div></section>;
}

export function AdminDashboard({ view }: { view: View }) {
  const [filters, setFilters] = useState({ range: "7d", search: "", repository: "all", employee: "all" });
  const { data, loading } = useOrganization(filters);
  const titles = { overview: ["Organization command center", "Security posture across every employee, repository and protected pull request."], employees: ["Employee security", "Compare exact leak types, clean-check accuracy and remediation performance."], repositories: ["Repository risk", "Prioritize repositories carrying the highest unresolved resource-leak debt."], incidents: ["Leak incidents", "Audit every finding attributed to its employee, branch, commit and pull request."] };
  return <>{loading && <div className="admin-loading"><i/> Syncing organization data</div>}<div className="admin-top"><div><span className="eyebrow">LeakGuard Organization</span><h1 className="page-title">{titles[view][0]}</h1><p className="subtitle">{titles[view][1]}</p></div><div className="org-chip"><span>CB</span><strong>{data.organization}<small>{data.source === "control-plane" ? "Live control plane" : "Demo organization data"}</small></strong></div></div><FilterBar data={data} filters={filters} setFilters={setFilters}/>{view === "overview" && <><Metrics data={data}/><DailyTrend data={data}/><div className="admin-section-title"><h2>Repository portfolio</h2><span>Updated from GitHub Actions</span></div><RepoPortfolio data={data}/><EmployeeTable data={data} compact/><IncidentTable data={data} limit={3}/></>}{view === "employees" && <><DailyTrend data={data}/><EmployeeDirectory data={data}/><EmployeeTable data={data}/></>}{view === "repositories" && <RepoPortfolio data={data} detailed/>}{view === "incidents" && <><Metrics data={data}/><IncidentTable data={data}/></>}</>;
}
