"use client";

import { Fragment, useEffect, useMemo, useRef, useState } from "react";
import { emptyOrganizationSnapshot, type OrganizationSnapshot } from "@/lib/organization";

type View = "overview" | "employees" | "repositories" | "incidents";

function useOrganization(filters: { range: string; search: string; repository: string; employee: string }, page: number, pageSize: number) {
  const [data, setData] = useState<OrganizationSnapshot>(() => ({ ...emptyOrganizationSnapshot, pagination: { ...emptyOrganizationSnapshot.pagination!, pageSize } }));
  const [loading, setLoading] = useState(true);
  const [refreshKey, setRefreshKey] = useState(0);
  const forceRefresh = useRef(false);
  useEffect(() => {
    const controller = new AbortController();
    const load = (force = false) => {
      const query = new URLSearchParams({ ...filters, page: String(page), pageSize: String(pageSize) });
      if (force) query.set("refresh", "1");
      setLoading(true);
      void fetch(`/api/organization?${query}`, { signal: controller.signal, cache: "no-store" })
        .then((r) => r.ok ? r.json() : Promise.reject(new Error("Organization request failed")))
        .then(setData)
        .catch((error: unknown) => { if (!(error instanceof DOMException && error.name === "AbortError")) console.error(error); })
        .finally(() => { if (!controller.signal.aborted) setLoading(false); });
    };
    const shouldForce = forceRefresh.current;
    forceRefresh.current = false;
    const timer = window.setTimeout(() => load(shouldForce), 200);
    const poll = window.setInterval(() => load(false), 15_000);
    return () => { window.clearTimeout(timer); window.clearInterval(poll); controller.abort(); };
  }, [filters.range, filters.search, filters.repository, filters.employee, page, pageSize, refreshKey]);
  return { data, loading, refresh: () => { forceRefresh.current = true; setRefreshKey((value) => value + 1); } };
}

function FilterBar({ data, filters, setFilters }: { data: OrganizationSnapshot; filters: { range: string; search: string; repository: string; employee: string }; setFilters: (next: typeof filters) => void }) {
  return <section className="filter-bar"><div><label htmlFor="org-search">Search employee, repo, error or reason</label><input id="org-search" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} placeholder="Try: employee, repository, sqlite..." autoComplete="off"/></div><div><label htmlFor="date-range">Date range</label><select id="date-range" value={filters.range} onChange={(event) => setFilters({ ...filters, range: event.target.value })}><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select></div><div><label htmlFor="repo-filter">Repository</label><select id="repo-filter" value={filters.repository} onChange={(event) => setFilters({ ...filters, repository: event.target.value })}><option value="all">All repositories</option>{data.repositories.map((repo) => <option value={repo.name} key={repo.name}>{repo.name}</option>)}</select></div><div><label htmlFor="employee-filter">Employee</label><select id="employee-filter" value={filters.employee} onChange={(event) => setFilters({ ...filters, employee: event.target.value })}><option value="all">All employees</option>{data.employees.map((employee) => <option value={employee.login} key={employee.login}>{employee.name}</option>)}</select></div><button onClick={() => setFilters({ range: "7d", search: "", repository: "all", employee: "all" })}>Reset</button><small>{data.pagination ? `${data.pagination.totalEmployees.toLocaleString()} employees · ${data.pagination.totalRepositories.toLocaleString()} repos · ${data.pagination.totalIncidents.toLocaleString()} incidents${filters.search ? ` matching “${filters.search}”` : ""}` : "Organization scope"}</small></section>;
}

function Pagination({ page, pageSize, total, onPage, onPageSize }: { page: number; pageSize: number; total: number; onPage: (page: number) => void; onPageSize: (size: number) => void }) {
  const pages = Math.max(1, Math.ceil(total / pageSize));
  const start = total === 0 ? 0 : (page - 1) * pageSize + 1;
  const end = Math.min(total, page * pageSize);
  return <nav className="admin-pagination" aria-label="Results pagination"><span>Showing <b>{start}-{end}</b> of <b>{total.toLocaleString()}</b></span><label>Rows <select value={pageSize} onChange={(event) => onPageSize(Number(event.target.value))}><option value={10}>10</option><option value={25}>25</option><option value={50}>50</option></select></label><button disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</button><strong>Page {page} / {pages}</strong><button disabled={page >= pages} onClick={() => onPage(page + 1)}>Next</button></nav>;
}

function DailyTrend({ data }: { data: OrganizationSnapshot }) {
  const max = Math.max(...data.trend.map((point) => point.opened), 1);
  return <section className="daily-panel"><header><div><span className="panel-kicker">Daily movement</span><h2>Is the team improving?</h2></div><div className="today-comparison"><b className="good-text">+{data.metrics.cleanRateDelta}%</b><small>clean accuracy</small><b className="good-text">{data.metrics.openDelta}</b><small>open errors</small></div></header><div className="daily-chart">{data.trend.map((point) => <div className="day-column" key={point.date}><span className="accuracy-label">{point.accuracy}%</span><div className="day-bars"><i className="bar-opened" style={{ height: `${Math.max(8, point.opened / max * 100)}%` }}/><i className="bar-resolved" style={{ height: `${Math.max(8, point.fixed / max * 100)}%` }}/></div><small>{point.date}</small></div>)}</div><footer><span><i className="bar-opened"/> errors opened</span><span><i className="bar-resolved"/> errors fixed</span><strong>Today: {data.trend.at(-1)?.fixed} fixed vs {data.trend.at(-1)?.opened} opened</strong></footer></section>;
}

function PersonalProgress({ employee, data }: { employee: OrganizationSnapshot["employees"][number]; data: OrganizationSnapshot }) {
  const points = data.trend.map((point, index) => ({ ...point, personal: Math.max(20, Math.min(100, employee.cleanRate - employee.cleanRateDelta + employee.cleanRateDelta * index / Math.max(1, data.trend.length - 1))) }));
  return <section className="personal-progress"><header><div><span className="panel-kicker">Personal progress</span><h3>{employee.name}&apos;s clean-check trend</h3></div><b className={employee.cleanRateDelta >= 0 ? "good-text" : "danger-text"}>{employee.cleanRateDelta >= 0 ? "+" : ""}{employee.cleanRateDelta}%</b></header><div className="personal-bars">{points.map((point) => <div key={point.date}><span style={{ height: `${point.personal}%` }}/><b>{Math.round(point.personal)}%</b><small>{point.date}</small></div>)}</div><footer>Calculated from this employee&apos;s clean PR checks in the selected period.</footer></section>;
}

function Metrics({ data }: { data: OrganizationSnapshot }) {
  const items = [["Employees", data.metrics.employees], ["Repositories", data.metrics.repositories], ["Open incidents", data.metrics.open], ["Blocked PRs", data.metrics.blockedPrs], ["GitHub failures", data.metrics.githubFailures ?? 0], ["LeakGuard scans", data.metrics.scans]];
  return <section className="admin-metrics">{items.map(([label, value]) => <div className="admin-stat" key={label}><small>{label}</small><b>{value}</b></div>)}</section>;
}

function EmployeeTable({ data, compact = false }: { data: OrganizationSnapshot; compact?: boolean }) {
  const employees = useMemo(() => [...data.employees].sort((a, b) => b.score - a.score), [data]);
  return <section className="admin-card"><div className="admin-card-head"><div><span className="panel-kicker">Team security performance</span><h2>{compact ? "Employee risk leaderboard" : "All employees"}</h2></div><span className="admin-help">Accuracy = clean PR checks / total PR checks</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Rank / employee</th><th>Repositories</th><th>Security score</th><th>Clean accuracy</th><th>D / L / P errors</th><th>Blocked PRs</th><th>Fix rate</th><th>Avg fix</th></tr></thead><tbody>{employees.map((employee, index) => <tr key={employee.login}><td><span className="rank">#{index + 1}</span><span className="avatar">{employee.avatar}</span><strong>{employee.name}<small>@{employee.login} · {employee.scans} checks</small></strong></td><td><b>{employee.repositories.length}</b><small>{employee.repositories.map((repo) => repo.repository).join(", ")}</small></td><td><b className={employee.score < 60 ? "danger-text" : "good-text"}>{employee.score}</b><span className="score-track"><i style={{ width: `${employee.score}%` }}/></span></td><td><b className={employee.cleanRate < 60 ? "danger-text" : "good-text"}>{employee.cleanRate}%</b></td><td><span className="severity-count definite">{employee.definite}</span><span className="severity-count likely">{employee.likely}</span><span className="severity-count possible">{employee.possible}</span></td><td>{employee.blocked}</td><td>{employee.fixRate}%<small>{employee.fixed} fixed</small></td><td>{employee.avgFixHours}h</td></tr>)}</tbody></table></div></section>;
}

function EmployeeDirectory({ data }: { data: OrganizationSnapshot }) {
  const ordered = [...data.employees].sort((a, b) => a.score - b.score);
  const [selected, setSelected] = useState(() => ordered[0]?.login ?? "");
  if (ordered.length === 0) {
    return <section className="employee-profile empty-directory"><span className="panel-kicker">Employee directory</span><h2>No employees match these filters</h2><p>Reset the employee, repository or search filter to restore the organization view.</p></section>;
  }
  const employee = data.employees.find((item) => item.login === selected) ?? ordered[0];
  const incidents = data.incidents.filter((item) => item.employee === employee.login);
  return <section className="directory-layout"><aside className="employee-list"><header><span className="panel-kicker">Directory</span><strong>{data.employees.length} employees on this page</strong></header>{ordered.map((item) => <button className={item.login === employee.login ? "active" : ""} key={item.login} onClick={() => setSelected(item.login)}><span className="avatar">{item.avatar}</span><span><strong>{item.name}</strong><small>@{item.login} · {item.repositories.length} repos · {item.open} open</small></span><b className={item.score < 60 ? "danger-text" : "good-text"}>{item.score}</b></button>)}</aside><article className="employee-profile"><header><div><span className="panel-kicker">Combined across all repositories</span><h2>{employee.name} <small>@{employee.login}</small></h2></div><span className={`profile-score ${employee.score < 60 ? "risk" : "healthy"}`}><b>{employee.score}</b><small>security score</small></span></header><div className="profile-kpis"><span><small>Repositories</small><b>{employee.repositories.length}</b></span><span><small>Clean-check accuracy</small><b>{employee.cleanRate}%</b></span><span><small>Open errors</small><b>{employee.open}</b></span><span><small>Fix rate</small><b>{employee.fixRate}%</b></span><span><small>Mean time to fix</small><b>{employee.avgFixHours}h</b></span><span><small>Repeat errors</small><b>{employee.repeats}</b></span></div><PersonalProgress employee={employee} data={data}/><div className="profile-columns"><div><h3>Repository-wise work accuracy</h3>{employee.repositories.map((repo) => <div className="repo-contribution" key={repo.repository}><strong>{repo.repository}<small>{repo.checks} PR checks · {repo.blocked} blocked · {repo.errors} errors</small></strong><span className="repo-accuracy"><b>{repo.cleanRate}%</b><i><em style={{ width: `${repo.cleanRate}%` }}/></i><small>clean accuracy</small></span></div>)}</div><div><h3>Recent attributed errors</h3>{incidents.length ? incidents.map((incident) => <div className="profile-incident" key={incident.id}><span className={`severity ${incident.confidence}`}>{incident.confidence}</span><strong>{incident.resource}<small>{incident.repository} · {incident.file}</small></strong><em>PR #{incident.pr}</em></div>) : <p className="empty-state">No recent errors for this employee.</p>}</div></div></article></section>;
}

function RepoPortfolio({ data, detailed = false }: { data: OrganizationSnapshot; detailed?: boolean }) {
  const [selected, setSelected] = useState("");
  const activeRepository = data.repositories.find((repo) => repo.name === selected) ?? data.repositories[0];
  const visibleRepositories = detailed ? (activeRepository ? [activeRepository] : []) : data.repositories.slice(0, 6);
  return <section className={detailed ? "repository-stack" : "repo-risk-grid"}>{detailed && <><div className="repository-browser-head"><div><span className="panel-kicker">Repository portfolio</span><h2>Choose a repository</h2></div><small>Click a container to inspect teams, employees and incidents</small></div><div className="repository-selector-grid">{data.repositories.map((repo) => <button className={`repo-select-card ${repo.risk} ${activeRepository?.name === repo.name ? "active" : ""}`} key={repo.name} onClick={() => setSelected(repo.name)}><span className="repo-symbol">R</span><span><strong>{repo.name}</strong><small>{repo.language} · {repo.members.length} employees</small></span><span><b>{repo.open}</b><small>open</small></span><em>{repo.risk}</em></button>)}</div></>}{visibleRepositories.map((repo) => {
    const incidents = data.incidents.filter((item) => item.repository === repo.name).slice(0, 8);
    if (!detailed) return <article className={`repo-risk ${repo.risk}`} key={repo.name}><div><span className="repo-symbol">R</span><span><strong>{repo.name}</strong><small>{repo.language} · {repo.members.length} employees</small></span></div><b>{repo.open}<small>open incidents</small></b><footer><span>{repo.blockedPrs} PRs blocked</span><em>{repo.risk} risk</em></footer></article>;
    return <article className={`repository-panel ${repo.risk}`} key={repo.name}><header><div><span className="repo-symbol">R</span><span><h2>{repo.name}</h2><small>{repo.language} · {repo.scans} incremental checks · {repo.members.length} contributors · {repo.teams.length} teams</small></span></div><div className="repo-summary"><span><b>{repo.open}</b><small>open errors</small></span><span><b>{repo.blockedPrs}</b><small>blocked PRs</small></span><em>{repo.risk} risk</em></div></header><div className="team-strip">{repo.teams.map((team) => <div className="team-card" key={team.name}><header><strong>{team.name}</strong><span className={team.cleanRate < 60 ? "danger-text" : "good-text"}>{team.cleanRate}% clean</span></header><small>Lead @{team.lead} · {team.members.length} members</small><div><span><b>{team.open}</b> open</span><span><b>{team.blocked}</b> blocked</span></div></div>)}</div><div className="repository-body"><div><h3>Employees in this repository</h3><table className="repo-member-table"><thead><tr><th>Employee</th><th>Checks</th><th>Accuracy</th><th>Errors</th><th>Blocked</th></tr></thead><tbody>{repo.members.map((member) => { const person = data.employees.find((item) => item.login === member.login); return <tr key={member.login}><td><span className="avatar">{person?.avatar}</span><strong>{person?.name}<small>@{member.login}</small></strong></td><td>{member.checks}</td><td><b className={member.cleanRate < 60 ? "danger-text" : "good-text"}>{member.cleanRate}%</b></td><td>{member.errors}</td><td>{member.blocked}</td></tr>; })}</tbody></table></div><div><h3>Repository incidents</h3>{incidents.length ? incidents.map((incident) => <div className="repo-incident" key={incident.id}><header><span className={`severity ${incident.confidence}`}>{incident.confidence}</span><b>{incident.id}</b><em>{incident.status}</em></header><strong>{incident.resource}</strong><small>@{incident.employee} · PR #{incident.pr}</small><code>{incident.file}</code><span className={`gate ${incident.gate}`}>{incident.gate === "blocked" ? "Merge blocked" : "Resolved"}</span></div>) : <p className="empty-state">No repository incidents.</p>}</div></div></article>;
  })}</section>;
}

function IncidentTable({ data, limit }: { data: OrganizationSnapshot; limit?: number }) {
  const [selected, setSelected] = useState<string | null>(null);
  const incidents = limit ? data.incidents.slice(0, limit) : data.incidents;
  return <section className="admin-card"><div className="admin-card-head"><div><span className="panel-kicker">GitHub enforcement</span><h2>Employee errors with reasons</h2></div><span className="admin-help">Click for reasoning and technical evidence</span></div><div className="admin-table-wrap"><table className="admin-table incident-table"><thead><tr><th>Incident</th><th>Employee / repository</th><th>Finding</th><th>Pull request</th><th>Gate</th></tr></thead><tbody>{incidents.map((incident) => <Fragment key={incident.id}><tr className="clickable-incident" onClick={() => setSelected(selected === incident.id ? null : incident.id)}><td><strong>{incident.id}</strong><small>{incident.detectedAt}</small></td><td><strong>@{incident.employee}</strong><small>{incident.repository} · {incident.branch}</small></td><td><span className={`severity ${incident.confidence}`}>{incident.confidence}</span><strong>{incident.resource}</strong><small>{incident.file}</small></td><td>#{incident.pr}</td><td><span className={`gate ${incident.gate}`}>{incident.gate === "blocked" ? "Blocked" : "Allowed"}</span></td></tr>{selected === incident.id && <tr className="incident-evidence"><td colSpan={5}><div><span><small>Why LeakGuard flagged it</small><strong>{incident.reason}</strong><em>Coaching context for @{incident.employee}</em></span><span><small>Technical witness path</small><ol>{incident.leakPath.map((step) => <li key={step}>{step}</li>)}</ol></span></div></td></tr>}</Fragment>)}</tbody></table></div></section>;
}

export function AdminDashboard({ view }: { view: View }) {
  const [filters, setFilters] = useState({ range: "7d", search: "", repository: "all", employee: "all" });
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  useEffect(() => setPage(1), [filters.range, filters.search, filters.repository, filters.employee]);
  const { data, loading, refresh } = useOrganization(filters, page, pageSize);
  const total = view === "repositories" ? data.pagination?.totalRepositories ?? data.repositories.length : view === "incidents" ? data.pagination?.totalIncidents ?? data.incidents.length : data.pagination?.totalEmployees ?? data.employees.length;
  const titles = { overview: ["Organization command center", "Security posture across every employee, repository and protected pull request."], employees: ["Employee security", "Compare exact leak types, clean-check accuracy and remediation performance."], repositories: ["Repository risk", "Prioritize repositories carrying the highest unresolved resource-leak debt."], incidents: ["Leak incidents", "Audit every finding attributed to its employee, branch, commit and pull request."] };
  return <>{loading && <div className="admin-loading"><i/> Syncing organization data</div>}<div className="admin-top"><div><span className="eyebrow">LeakGuard Organization</span><h1 className="page-title">{titles[view][0]}</h1><p className="subtitle">{titles[view][1]}</p></div><div className="org-live-controls"><div className="org-chip"><span>CB</span><strong>{data.organization}<small>Live SQLite control plane · refreshes every 15s</small></strong></div><button onClick={refresh} disabled={loading}>{loading ? "Syncing…" : "Refresh GitHub"}</button></div></div>{data.syncError && <div className="sync-warning"><b>GitHub sync needs attention:</b> {data.syncError}. Stored Action reports are still available.</div>}<FilterBar data={data} filters={filters} setFilters={setFilters}/>{view === "overview" && <><Metrics data={data}/><DailyTrend data={data}/><div className="admin-section-title"><h2>Repository portfolio</h2><span>Last DB update {new Date(data.generatedAt).toLocaleTimeString()}</span></div><RepoPortfolio data={data}/><EmployeeTable data={data} compact/><IncidentTable data={data} limit={3}/></>}{view === "employees" && <><DailyTrend data={data}/><EmployeeDirectory data={data}/><EmployeeTable data={data}/></>}{view === "repositories" && <RepoPortfolio data={data} detailed/>}{view === "incidents" && <><Metrics data={data}/><IncidentTable data={data}/></>}<Pagination page={page} pageSize={pageSize} total={total} onPage={setPage} onPageSize={(size) => { setPageSize(size); setPage(1); }}/></>;
}
